---
version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql-company
    restart: always
    environment:
      MYSQL_DATABASE: 'company'
      MYSQL_USER: 'lazar'
      MYSQL_PASSWORD: 'company'
      MYSQL_ROOT_PASSWORD: 'company'
    ports:
      - '3306:3306'
    volumes:
      - ~/.apps/mysql_company:/var/lib/mysql

  postgres:
    image: postgres
    container_name: postgres-company
    ports:
      - 5432:5432
    volumes:
      - ~/.apps/postgres_company:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=lazar
      - POSTGRES_PASSWORD=company
      - POSTGRES_DB=company

  adminer:
    image: adminer
    container_name: adminer-company
    restart: always
    ports:
      - 8080:8080

  localstack:
    image: localstack/localstack:latest
    container_name: localstack-company
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=eu-central-1
    volumes:
      - '~/.company/localstack:/.localstackCompany'
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'

  localstack-test:
    image: localstack/localstack:latest
    container_name: localstack-test-company
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=eu-central-1
      - DATA_DIR=~/.company/test/localstack/data
    volumes:
      - '~/.company/test/localstack:/.localstackCompany'
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '7563-7599:4563-4599'
      - '7055:8080'
